[package]
name = "crane"
version = "0.0.0"
edition = "2021"

[dependencies]
windows = { version = "0.58.0", features = ["Win32_UI_Shell"] }
serde = { version = "1.0.214", features = ["derive"] }
serde_json = { version = "1.0.132" }
